<?php
// {{NAME}} – emails car orders / import requests. Generated by build.js from src/config.js.
header('Content-Type: application/json; charset=utf-8');
header('X-Robots-Tag: noindex');

$TO   = '{{TO}}';
$FROM = '{{FROM}}';
$NAME = '{{NAME}}';

function out($ok, $msg = '') { echo json_encode(['ok' => $ok, 'message' => $msg]); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); out(false, 'Method not allowed'); }

$raw  = file_get_contents('php://input');
$data = json_decode($raw, true);
if (!is_array($data)) $data = $_POST;

// Honeypot + basic flood protection
if (!empty($data['website'])) out(true);
session_start();
$now = time();
$_SESSION['em_hits'] = array_filter($_SESSION['em_hits'] ?? [], fn($t) => $t > $now - 600);
if (count($_SESSION['em_hits']) >= 6) { http_response_code(429); out(false, 'Too many requests. Please WhatsApp us instead.'); }
$_SESSION['em_hits'][] = $now;

$clean = function ($v, $max = 500) {
  $v = is_string($v) ? $v : '';
  $v = str_replace(["\r", "\0"], '', trim($v));
  return mb_substr(strip_tags($v), 0, $max);
};
$name  = $clean($data['name'] ?? '', 100);
$phone = $clean($data['phone'] ?? '', 30);
$email = filter_var($clean($data['email'] ?? '', 150), FILTER_VALIDATE_EMAIL) ?: '';
if ($name === '' || !preg_match('/^[0-9+\s()-]{9,20}$/', $phone)) { http_response_code(422); out(false, 'Please enter your name and a valid phone number.'); }

$labels = [
  'ref' => 'Reference', 'type' => 'Type', 'car' => 'Car', 'variant_name' => 'Version / spec', 'price' => 'Est. landed price',
  'make' => 'Make', 'model' => 'Model', 'other_car' => 'Car (typed)', 'fuel' => 'Fuel', 'transmission' => 'Transmission',
  'origin' => 'Import from', 'year' => 'Year', 'budget' => 'Budget', 'mileage' => 'Max mileage', 'colour' => 'Colour', 'timeline' => 'Timeline',
  'name' => 'Name', 'phone' => 'Phone / WhatsApp', 'email' => 'Email', 'town' => 'Town', 'notes' => 'Notes', 'page' => 'Page',
];
$lines = [];
foreach ($labels as $k => $label) {
  $v = $k === 'email' ? $email : $clean($data[$k] ?? '', $k === 'notes' ? 2000 : 300);
  if ($v !== '') $lines[] = str_pad($label . ':', 20) . $v;
}
$ref  = $clean($data['ref'] ?? '', 20) ?: ('EM-' . strtoupper(substr(md5($now . $phone), 0, 6)));
$type = $clean($data['type'] ?? 'Order', 40);
$car  = $clean($data['car'] ?? ($data['make'] ?? '') . ' ' . ($data['model'] ?? ''), 120);
$waPhone = preg_replace('/\D/', '', $phone);
if (str_starts_with($waPhone, '0')) $waPhone = '254' . substr($waPhone, 1);

$body = "New {$type} from the {$NAME} website\n\n" . implode("\n", $lines) .
        "\n\nReply on WhatsApp: https://wa.me/{$waPhone}\nReceived: " . date('D j M Y, H:i') . "\n";
$subject = "=?UTF-8?B?" . base64_encode("[{$ref}] {$type}: {$car} – {$name}") . "?=";
$headers = "From: {$NAME} Website <{$FROM}>\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n";
if ($email) $headers .= "Reply-To: {$email}\r\n";

$sent = @mail($TO, $subject, $body, $headers, "-f{$FROM}");

// Acknowledge the customer
if ($sent && $email) {
  $ack = "Hi {$name},\n\nThank you for your interest in importing with {$NAME}. We have received your {$type}. Your reference is {$ref}.\n\n" . implode("\n", $lines) .
         "\n\nOur team will contact you shortly on {$phone} with a free, all-inclusive landed quote.\n\n{$NAME}\nWhatsApp: https://wa.me/{{WA}}  ·  {{PHONE}}\n";
  @mail($email, "=?UTF-8?B?" . base64_encode("Your {$NAME} request {$ref}") . "?=", $ack,
        "From: {$NAME} <{$FROM}>\r\nReply-To: {$TO}\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n", "-f{$FROM}");
}
out($sent, $sent ? 'Sent' : 'Email could not be sent');
